[package]
name = "rcc-bitcoin"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.29.2"
xyzpub = "0.3.0"
thiserror = "1.0.31"
