[package]
name = "rcc_signer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.1.0"
hex = "0.4.3"
thiserror="1.0"
bytes = "1"
indexmap = "1.8.1"
k256 = {version = "0.11.3", features=["ecdsa", "keccak256"] }
bs58="0.4.0"
